# Generated by Django 4.0 on 2021-12-15 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='school',
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
